[package]
name = "asciidoc-zed-lsp"
version = "0.0.1"
edition = "2024"
repository = "https://github.com/zheylmun/asciidoxide"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
