id = "asciidoc-lsp"
name = "Asciidoc LSP"
version = "0.0.1"
schema_version = 1
authors = ["Zachary Heylmun <zheylmun@gmail.com>"]
description = "Asciidoc language server protocol support for Zed."
repository = "https://github.com/zheylmun/asciidoxide"

[language_servers.asciidoc-language-server]
name = "Asciidoc Language Server"
languages = ["AsciiDoc"]

[grammars.asciidoc]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
rev = "0ecc13042b7352ddc3f7b8b31432e262711d44e4"
path = "tree-sitter-asciidoc"

[grammars.asciidoc_inline]
repository = "https://github.com/cathaysia/tree-sitter-asciidoc"
rev = "0ecc13042b7352ddc3f7b8b31432e262711d44e4"
path = "tree-sitter-asciidoc_inline"
